version: "3"

services:
  mongo:
    image: mongo:6

  app:
    build: .
    environment:
      CRON_RULE: ${APP_CRON_RULE:-"0 0 0 * * *"}
      GOOGLE_API_KEY: ${APP_GOOGLE_API_KEY:?"APP_GOOGLE_API_KEY is required."}
