services:
  mongo:
    volumes:
      - mongo_data:/data/db
    ports:
      - ${MONGO_PORT:-27017}:27017

  app:
    build:
      dockerfile: dev.Dockerfile
    volumes:
      - .:/opt/app:ro

volumes:
  mongo_data:
